public class newcalander {
  /*
    @AuraEnabled
    public static list<Program__c> getAllprograms(){
      list<Program__c> programlist =[SELECT Id, Name, Faculty_Name__c, Program_Time__c, Program_Type__c, Contact__c, Program_Date__c FROM Program__c where createdById=:Userinfo.getUserId()] ;
      return programlist;
    }
    
    
    @AuraEnabled
    public static void updateprogram(string programid,string programdate){
    system.debug(programid);
        system.debug(programdate);
        string programdatelist = programdate.replace('T',' ');
       
  system.debug(programdatelist);
    Event e= new event(id = programid);
    e.StartDateTime = DateTime.valueof(programdatelist);
    update e;
   
    }
    */

}